### ISSUE TITLE
No Display with HDMI to VGA Converter

### ISSUE THREAD

**Issue by CreativeWolf** [beagleboard/beagleboard-x15#8]
I'm trying to connect a display using HDMI to VGA Converter but not getting any output on display.

Any thoughts please?

**Comment by jadonk** [comment]
What model converter are you using? What are you getting back from the EDID and the active display mode?

**Comment by JamPsym** [comment]
Have the same problem. Is it possible to force hdmi output somehow? As I can see the problem is that EDID cant be red: "omapdss error: HDMI I2C timeout reading EDID". Probably I'm naive but in raspbian I could do this by adding some line in /boot/config.txt file.

**Comment by CreativeWolf** [comment]
Not sure how I missed the notifications on this. Was cleaning up and found the board again. Has anyone made any progress on this issue at all?

@jadonk It's an off the shelf converter and I'm not sure how to see the EDID data.

**Comment by CreativeWolf** [comment]
Had to tinker the HDMI to VGA adapter to use external power, in my case, powering it from the X15's USB and that worked.
